apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr-frontend-deployment
  namespace: rr-app 
  labels:
    app: frountend
    env: development
  annotations:
    kubernetes.io/change-cause: "Initial release with rr-frontend:v3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        environment: development

    spec:
      containers:
      - name: rr-frontend--container
        image: xrootms/rr-frontend:v3

---
apiVersion: v1
kind: Service
metadata:
  name: rr-frontend-service

spec:
  type: ClusterIP   
  selector:
    app: frontend

  ports:
  - port: 80
    targetPort: 80
