apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr-frontend-deployment
  namespace: rr-app 
  labels:
    app: frountend
    env: development
  annotations:
    kubernetes.io/change-cause: "Initial release with rr-frontend:v3"

spec:
  replicas: 1
  revisionHistoryLimit: 10           # old replicasets kept for rollback (default: 10)
  minReadySeconds: 5                 # seconds pods must be ready before counted avilable (default:0)
  progressDeadlinesSeconds: 300      # mark rollout stalled after N seconds (default: 600)
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1                    # allow 1 extra pod during update. (default is 25 %)
      maxUnavailable: 0              # keep all existing pods available. (default is 25%)

  template:
    metadata:
      labels:
        app: frontend
        environment: development

    spec:
      containers:
      - name: rr-frontend--container
        image: xrootms/rr-frontend:v3

---
apiVersion: v1
kind: Service
metadata:
  name: rr-frontend-service

spec:
  type: ClusterIP   
  selector:
    app: frontend

  ports:
  - port: 80
    targetPort: 80
